#!/usr/bin/env sh

rm -fr src/*.o src/*.so autom4te.cache config.log config.status

# sync Version number
RLIBKRIGING_PATH="libKriging/bindings/R/rlibkriging"
VERSION=`grep "Version:" $RLIBKRIGING_PATH/DESCRIPTION`
sed -i.bak "s/Version:.*/$VERSION/g" DESCRIPTION
rm -f DESCRIPTION.bak
