# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
bench_solvetri <- function(n, X, y) {
    .Call(`_rlibkriging_bench_solvetri`, n, X, y)
}

#' @export
bench_cholsym <- function(n, X) {
    .Call(`_rlibkriging_bench_cholsym`, n, X)
}

#' @export
#' @export
bench_invsympd <- function(n, X) {
    .Call(`_rlibkriging_bench_invsympd`, n, X)
}

#' @export
bench_qr <- function(n, X) {
    .Call(`_rlibkriging_bench_qr`, n, X)
}

#' @export
bench_LogLik <- function(n, ordinaryKriging, theta) {
    .Call(`_rlibkriging_bench_LogLik`, n, ordinaryKriging, theta)
}

#' @export
bench_LogLikGrad <- function(n, ordinaryKriging, theta) {
    .Call(`_rlibkriging_bench_LogLikGrad`, n, ordinaryKriging, theta)
}

new_Kriging <- function(y, X, kernel, regmodel = "constant", normalize = FALSE, optim = "BFGS", objective = "LL", parameters = NULL) {
    .Call(`_rlibkriging_new_Kriging`, y, X, kernel, regmodel, normalize, optim, objective, parameters)
}

kriging_model <- function(k) {
    .Call(`_rlibkriging_kriging_model`, k)
}

kriging_predict <- function(k, X, stdev = TRUE, cov = FALSE) {
    .Call(`_rlibkriging_kriging_predict`, k, X, stdev, cov)
}

kriging_simulate <- function(k, nsim, seed, X) {
    .Call(`_rlibkriging_kriging_simulate`, k, nsim, seed, X)
}

kriging_update <- function(k, y, X, normalize = FALSE) {
    invisible(.Call(`_rlibkriging_kriging_update`, k, y, X, normalize))
}

kriging_logLikelihood <- function(k, theta, grad = FALSE, hess = FALSE) {
    .Call(`_rlibkriging_kriging_logLikelihood`, k, theta, grad, hess)
}

kriging_leaveOneOut <- function(k, theta, grad = FALSE) {
    .Call(`_rlibkriging_kriging_leaveOneOut`, k, theta, grad)
}

kriging_logMargPost <- function(k, theta, grad = FALSE) {
    .Call(`_rlibkriging_kriging_logMargPost`, k, theta, grad)
}

linear_regression <- function(y, X) {
    .Call(`_rlibkriging_linear_regression`, y, X)
}

linear_regression_optim <- function(y, X) {
    .Call(`_rlibkriging_linear_regression_optim`, y, X)
}

linear_regression_predict <- function(linearRegression, X) {
    .Call(`_rlibkriging_linear_regression_predict`, linearRegression, X)
}

