name: R-CMD-INSTALL

on:
  tags:        
    - '*'
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * SAT'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        R: [ '4.3' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
          rtools-version: '43'

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.24.x'

      - run: |
          cd ..; R CMD INSTALL --build rlibkriging 
          mkdir rlibkriging/R-${{ matrix.R }}
          mv rlibkriging_*.* rlibkriging/R-${{ matrix.R }}/.
        shell: bash
        name: R CMD INSTALL

      - uses: actions/upload-artifact@v2
        with:
          path: ./R-*

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./R-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
