name: R-CMD-INSTALL-build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * SAT'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        R: [ 'release', 'next' ]
        cc: [ 'default', 'gcc-15' ]

    runs-on: 'ubuntu-latest'
    container:
      image: ubuntu:plucky
      
    steps:
      - name: Install gcc-15
        if: matrix.cc == 'gcc-15'
        run: |
          apt update && apt install -y software-properties-common
          add-apt-repository ppa:ubuntu-toolchain-r/test && apt update
          apt search gcc-15
          apt install -y gcc-15 g++-15
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 15 --slave /usr/bin/g++ g++ /usr/bin/g++-15
          update-alternatives --set gcc /usr/bin/gcc-15
          gcc --version
          g++ --version

      - name: Install gcc
        if: matrix.cc != 'gcc-15'
        run: |
          apt update
          apt install -y gcc g++
          gcc --version
          g++ --version

      - name: Install git
        run: apt install -y git

      - name: Get sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install R
        run: apt install -y r-base r-cran-devtools
        #uses: r-lib/actions/setup-r@v2
        #with:
        #  r-version: ${{ matrix.R }}
        #  rtools-version: ''

      - name: Install R deps
        run: R -e "install.packages(c('Rcpp','RcppArmadillo','DiceKriging'))"
        #uses: r-lib/actions/setup-r-dependencies@v2

      - name: Setup cmake
        run: apt install -y cmake
        #uses: jwlawson/actions-setup-cmake@v1.13
        #with:
        #  cmake-version: '3.24.x'

      - name: Install rlibkriging
        run: |
          cd ..; R CMD INSTALL --build rlibkriging 
          mkdir rlibkriging/R${{matrix.R}}-${{ matrix.cc }}
          mv rlibkriging_*.* rlibkriging/R${{matrix.R}}-${{ matrix.cc }}/.
        shell: bash

      - name: Test rlibkriging
        run: R -e "library(rlibkriging); X=matrix(runif(10)); Kriging(sin(X),X,'gauss')"

      - uses: actions/upload-artifact@v4
        with:
          path: ./R*
