name: Check install_github

on:
  push:
    branches: [ master ]
    tags: [ '*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  install_github:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        R: [3.6, 4.1, 4.2]

    runs-on: ${{ matrix.os }}
       
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}

    - run: Rscript -e "install.packages('devtools')"
      shell: bash

    - run: Rscript -e "devtools::install_github('libKriging/rlibkriging')"
      shell: bash
