name: rhub-local_check

on:
  push:
    branches: [ master ]
    tags: [ '*.*' ]
  pull_request:
    branches: [ master ]

env:
  DEBUG_CI: true

jobs:
  rhub-local_check:
    strategy:
      fail-fast: false
      matrix:
        #rhub::local_check_linux_images()
        rhubos: [ 'debian-clang-devel','debian-gcc-devel','debian-gcc-devel-nold','debian-gcc-patched','debian-gcc-release','fedora-clang-devel','fedora-gcc-devel','rocker-gcc-san','ubuntu-gcc-devel','ubuntu-gcc-release','ubuntu-rchk' ]

    runs-on: ubuntu-latest
    container:
      image: rhub/${{ matrix.rhubos }}
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  submodules: recursive
        run: |
          git submodule update --init --recursive
        #shell: bash
        #run: |
        #  pushd ..
        #  git clone --recurse-submodules https://github.com/libKriging/rlibkriging
        #  popd

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          rtools-version: '42'

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: setup for CRAN
        shell: bash
        run: ./tools/setup.sh

      - name: R CMD build
        shell: bash
        env: # this alias helps to reuse following line as script
          OS: ${{ matrix.os }}
        run: |
          pushd ..
          R CMD build rlibkriging 
          mkdir rlibkriging/CRAN-$OS
          mv rlibkriging_*.* rlibkriging/CRAN-$OS/.
          popd

      - name: R CMD check
        shell: bash
        env:
          OS: ${{ matrix.os }}
        run: |
          R CMD check --as-cran --no-manual CRAN-$OS/rlibkriging* || (
            test -f rlibkriging.Rcheck/00install.out && cat rlibkriging.Rcheck/00install.out | sed -e 's/^/00install.out| /' && echo "[The error may be shown before 00install.out| listing"; 
            exit 1
          )

      - uses: actions/upload-artifact@v2
        with:
          path: ./CRAN-*

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./CRAN-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
