name: rhub-local_check

on:
  push:
    branches: [ master ]
    tags: [ '*.*' ]
  pull_request:
    branches: [ master ]

env:
  DEBUG_CI: true

jobs:
  rhub-local_check:
    strategy:
      fail-fast: false
      matrix:
        #rhub::local_check_linux_images()
        rhubos: [ 'debian-clang-devel','debian-gcc-devel','debian-gcc-devel-nold','debian-gcc-patched','debian-gcc-release','fedora-clang-devel','fedora-gcc-devel','rocker-gcc-san','ubuntu-gcc-devel','ubuntu-gcc-release','ubuntu-rchk' ]

    runs-on: ubuntu-latest
    container:
      image: rhub/${{ matrix.rhubos }}
      options: --user root

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Add dependencies
        shell: bash
        run: |
          echo "`cat /etc/*-release | grep ID | cut -d= -f2 | head -1 | tr -d '\t'`"; \
            if [ `cat /etc/*-release | grep ID | cut -d= -f2 | head -1 | tr -d '\t'` = "fedora" ]; \
            then dnf install -y git cmake gfortran libcurl-devel libxml2-devel openssl-devel fontconfig-devel; \
            else apt-get install -y git cmake gfortran libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libxml2-dev libssl-dev libfontconfig1-dev; \
            fi

      - uses: actions/checkout@v3.0.2
      #  with:
      #    submodules: recursive
      - name: Checkout submodules
        shell: bash
        run: |
          git config --global --add safe.directory /__w/rlibkriging/rlibkriging
          git submodule update --init --recursive

      - name: Install devtools
        shell: bash
        run: |
          # Add --insecure to workaround missing certificates on Windows
          # --header is not required by an useful example if the repo becomes private 
          curl --insecure --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -LO https://raw.githubusercontent.com/libKriging/rlibkriging/${{ env.BRANCH_NAME }}/tools/install_packages.R
          Rscript --no-save ./install_packages.R devtools

      - name: install_github from ${{ env.BRANCH_NAME }}
        shell: bash
        run: Rscript -e "library(devtools); install_github('libKriging/rlibkriging', ref='${{ env.BRANCH_NAME }}'); if (!library('rlibkriging', character.only=TRUE, logical.return=TRUE)) quit(status=1, save='no')"

